package com.surgeon.weaving.core.interfaces;

import com.surgeon.weaving.core.SurgeonMethod;

/**
 * The replace manager for the same namespace.The implements generated by AnnotationProcesscor.
 */
public interface IMaster {
    /**
     * @param name The key of SurgeonMethod
     */
    SurgeonMethod find(String name);
}
