package com.surgeon.weaving.core.interfaces;

import com.surgeon.weaving.core.SurgeonMethod;

/**
 * The replace manager for the same namespace.The subclass generated by AnnotationProcesscor.
 */
public interface IMaster {
    /**
     * @param function The key of SurgeonMethod
     */
    SurgeonMethod find(String function);
}
